###############################################################
# DHCP Server Configuration - Node 2 (Local Management Station)
###############################################################

# Settings for the Layer 2 VPN Subnet
subnet 10.8.0.0 netmask 255.255.255.0 {
  range 10.8.0.10 10.8.0.50;           # Range of IPs for VPN Clients
  
  # option routers 10.8.0.1;           # Default Gateway (Commented out for L2 bridging)
  option domain-name-servers 8.8.8.8;  # Public Google DNS
  
  default-lease-time 600;              # 10 minutes default lease
  max-lease-time 7200;                 # 2 hours maximum lease
  
  authoritative;                       # This server is the primary DHCP for the subnet
}